### ISSUE TITLE
[✍️ Dev Log ] 이석준 2021-06-30

### ISSUE THREAD

**Issue by CodingGorani** [codestates/re-collect-client#21]
### 오늘은 어떻게 프로젝트에 기여했나요?
- 반응형 페이지 시작했다.
- 카테고리박스 그리드를 재정렬했다.
- 리액트 셀렉트 라이브러리에 대해서 공부했다.
### 오늘의 프로젝트에서 힘든 점은 무엇인가요?
- 카테고리박스 그리드와 알람, 검색이 들어있는 요소의 라인을 맞추는게 힘들었다.
- 이 둘에 각각 다른 열 개수를 가진 그리드를 적용해 해결했다.
```css

&__nav {
    display: grid;
    grid-template-columns: 1fr 30px 1fr 30px 1fr 30px 1fr;
    height: 70px;
  }
/*알람과 검색이 들어가는 부분*/

&__alarm {
    grid-column-start: 1;
    grid-column-end: 6;
}

&__search {
    grid-column-start: 7;
    grid-column-end: 8;
}

/*북마크 카테고리박스 들이 들어가는 부분*/
&__bookmarks {
   display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-auto-rows: 1fr;
    gap: 30px;
}

```
### 내일은 프로젝트에 기여하기 위해 무엇을 해야 하나요?
1. [ ]  반응형 모바일 페이지에 들어가는 요소를 만들 것이다.
2. [ ]  리콜렉트 컴포넌트를 만들 것이다.
3. [ ]  드래그앤 드롭 구현을 공부해 볼 것이다.
